name: docs

on:
  push:
    branches:
      - master
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: qoqa/action-s3-cp@v1.1
        env:
          AWS_S3_BUCKET: 'zebrunner-stage'
          AWS_ACCESS_KEY_ID: ${{ secrets.DOCS_AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DOCS_AWS_SECRET }}
          AWS_REGION: 'eu-west-1'
          AWS_S3_PATH: '/_common/docs/agents/README.md'
          FILE: 'README.md'
